### ISSUE TITLE
Muted tests still causing build to fail

### ISSUE THREAD

**Issue by aaron-0** [carlpett/xUnit-TeamCity#21]
I have a unit test that is failing that we have muted.

Even though the unit test is muted the build is still being counted as failed as the xunit build step has in the log:
Test runner exited with non-zero status!

I thought unit test runners were supposed to return 0 even when unit tests fail and then it is build failure conditions(e.g at least one test failed) that come through and mark the status as failed. I might be wrong about this...

**Comment by carlpett** [comment]
@aaron-0 Thanks for reporting! I _think_ this will be solved by #20 - it turns out that xUnit's return code (pre v2.2) was actually the number of failed tests, not whether the program worked or not. So this would be misinterpreted by TeamCity. 
I haven't received any feedback from the original PR author for almost three weeks, so I will go ahead and merge this.

**Comment by aaron-0** [comment]
Cool, when are you planning on releasing that version?

**Comment by carlpett** [comment]
This code is included in the [prerelease](https://github.com/carlpett/xUnit-TeamCity/releases/tag/v1.2.0-alpha1) I uploaded recently, so you may want to try that and see if it works for you.
I still have one bug fix and one feature planned for this release, but I'm currently awaiting a response from Jetbrains regarding their API, so I'm not sure exactly when it will be done. Hopefully most of the work will be completed anyway during the weekend, but it may take another week, depending on their answer.

**Comment by aaron-0** [comment]
Awesome thanks

**Comment by carlpett** [comment]
A final build of 1.2 has now been released!

**Comment by aaron-0** [comment]
works great thanks
